/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyList {
    }
    interface MyListItem {
    }
}
declare global {
    interface HTMLMyListElement extends Components.MyList, HTMLStencilElement {
    }
    var HTMLMyListElement: {
        prototype: HTMLMyListElement;
        new (): HTMLMyListElement;
    };
    interface HTMLMyListItemElement extends Components.MyListItem, HTMLStencilElement {
    }
    var HTMLMyListItemElement: {
        prototype: HTMLMyListItemElement;
        new (): HTMLMyListItemElement;
    };
    interface HTMLElementTagNameMap {
        "my-list": HTMLMyListElement;
        "my-list-item": HTMLMyListItemElement;
    }
}
declare namespace LocalJSX {
    interface MyList {
    }
    interface MyListItem {
    }
    interface IntrinsicElements {
        "my-list": MyList;
        "my-list-item": MyListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-list": LocalJSX.MyList & JSXBase.HTMLAttributes<HTMLMyListElement>;
            "my-list-item": LocalJSX.MyListItem & JSXBase.HTMLAttributes<HTMLMyListItemElement>;
        }
    }
}
